typography_spectrum: 0.4324063794197882
content_rating:
  adult: false
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.9481017782602355
  lightness: 0.9022474376565316
  saturation: 0.7303740886374606
  rhythmicContrast: 0.06793519783929569
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.013798413850271252
author:
  name: Jason
  url: jasonhendry.com
  email: jasonhendry@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7ddaf1ca-115a-4073-abf3-65407234d290.svg
name: jasonhendry
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/582fbb60-5944-4dd9-9b37-7f7f8859c5a5.svg
title: iLikeBorscht
